using System;

namespace Dapper;

/// <summary>
/// Attribute for setting a column key that is not generated by the database
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ExplicitKeyAttribute : Attribute
{
}
